services:
  - type: web
    name: ana-conecta
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && chmod +x backend/main.py"
    startCommand: "gunicorn backend.main:app"
    repo: <your-repo-url>
